export const growthContent = {
  bg: {
    title: 'От запитване', titleSecond: 'до нов клиент.',
    intro: 'Помагам на работещи бизнеси да представят по-ясно офертата си, да отговарят навреме и да проследяват всяко запитване. Подреждаме сайта, съдържанието и продажбите според това къде се губи клиентът.',
    cta: 'Заявете безплатен разговор', note: '30 минути по телефона · Без плащане и без ангажимент',
    promises: ['Ясен обхват и цена', 'Изпълнение, не само съвети', 'Работите директно с мен'],
    differenceTitle: 'Къде се затруднява', differenceSecond: 'Вашият бизнес?',
    differenceIntro: 'Избираме проблема с най-голямо значение за Вас. Ето какво можем да подобрим според нуждите на бизнеса.',
    principles: [
      { title: 'Хората не разбират защо да изберат Вас', text: 'Изясняваме за кого е услугата Ви, какво получава клиентът и защо си струва. Пренаписваме офертата и ключовите текстове с конкретни ползи и ясна следваща стъпка.' },
      { title: 'Имате посещения, но малко запитвания', text: 'Проверяваме страницата на телефон, подредбата, доказателствата, бутоните и формата. Поправяме пречките пред обаждането, запитването или записването.' },
      { title: 'Запитванията се губят в съобщенията', text: 'Събираме контактите и офертите на едно място. Всеки разговор има отговорник, етап и следваща задача, за да знаете на кого още трябва да отговорите.' },
      { title: 'Публикувате, без да е ясно с каква цел', text: 'Подреждаме темите, посланията и призивите за действие около услугите Ви. Подготвяме план и шаблони, които Вашият екип може да използва последователно.' },
      { title: 'Повтарящите се задачи Ви бавят', text: 'Настройваме подходящи автоматизации: известия за ново запитване, напомняния за оферти и обобщения. Използваме изкуствен интелект там, където пести работа и може да бъде проверен.' },
      { title: 'Всичко минава през собственика', text: 'Описваме кой какво прави и кога. Даваме кратки инструкции, обучаваме хората и следим няколко полезни показателя вместо куп несвързани отчети.' },
    ],
    offerTitle: 'Не продавам пакет.', offerSecond: 'Продавам две седмици.',
    offerIntro: 'Избираш едно нещо, което те бави най-много. Записваме го писмено, преди да платиш. После две седмици работя по него.',
    priceLabel: 'Еднократно за първите 3 клиента',
    scope: [
      'Разговор, в който минаваме през бизнеса ти и избираме кое те бави най-много в момента.',
      'Писмен обхват преди плащането: какво ще направя, докъде стига и как ще проверим, че е свършено.',
      'Две седмици работа върху избраното — сайт, страница, оферта, текстове, реклама, съдържание, автоматизация или вътрешен процес.',
      'Всичко направено остава твое: достъпи, файлове, текстове и настройки, регистрирани на твое име.',
      'Тест с реален случай от начало до край, не на теория.',
      'обучение и кратки инструкции',
    ],
    offerTiming: 'Две седмици работа от договорената начална дата.',
    offerPayment: '250 € се заплащат предварително, след като обхватът е записан писмено.',
    offerWhy: 'Ако след двете седмици договорените цели не са постигнати, продължаваме да работим по тях напълно безплатно, докато ги постигнем. Няма допълнителна такса за работата ни.',
    offerCta: 'Да обсъдим стартовия проект',
    guideTitle: 'Преди да говорим,', guideSecond: 'проверете сами.',
    guideIntro: '„12 проверки: къде губите запитвания“ — кратко практическо ръководство за офертата, сайта и отговора към клиента. Отбележете пропуските и изберете една стъпка за тази седмица.',
    guideBullets: ['12 въпроса с конкретни действия', 'Пример за първи отговор и последващо свързване', 'Работен лист за първото подобрение'],
    guideRead: 'Прочетете чеклиста', guideDownload: 'Свалете PDF', guideNote: 'Безплатно · Без регистрация · На български',
    aboutTitle: 'Човекът, с когото', aboutSecond: 'ще работите.',
    aboutText: 'Аз съм Георги Кърчев, основател на KARCHX. Съчетавам работа по сайтове, съдържание, маркетинг и автоматизации. Ще работите директно с мен — от първия разговор до предаването. Ако вече имате дизайнер, маркетолог или търговец, включваме го с ясни задачи и отговорности.',
    role: 'Георги Кърчев', roleDetail: 'Основател на KARCHX · Пловдив / онлайн за България',
    faqTitle: 'Отговори преди решението.',
    faqs: [
      { q: 'За какъв бизнес е подходящо?', a: 'За работещ бизнес с реални клиенти, услуга или продукт и човек, който може да участва във внедряването. Най-полезно е, когато вече има посещения или запитвания, но обработката им е разпокъсана. Ако тепърва търсите какво да продавате, този стартов проект вероятно не е първата Ви стъпка.' },
      { q: 'Безплатен ли е първият разговор?', a: 'Да. Той е до 30 минути, по телефона и без ангажимент за покупка. Обсъждаме бизнеса и преценяваме дали има подходяща задача. Подробният преглед и изпълнението са част от платения проект.' },
      { q: 'Какво включва цената 250 € и кога се плаща?', a: 'Цената е за две седмици работа по описания обхват и важи за първите 3 клиента. Плаща се изцяло предварително. Преди плащането записваме целите, как ще измерим изпълнението им, задачите и началната дата. Евентуални външни разходи се съгласуват отделно.' },
      { q: 'Какво става, ако целите не са постигнати за две седмици?', a: 'Продължаваме да работим по предварително договорените цели напълно безплатно, докато ги постигнем. Този ангажимент е за целите, записани преди старта. Нови задачи извън тях се обсъждат отделно. Цените на външни инструменти не са такса за нашата работа и се уточняват предварително.' },
      { q: 'Как определяме целите?', a: 'В началото преглеждаме бизнеса и наличните данни. Записваме конкретните цели и начина, по който ще проверим постигането им: например време за отговор, проследяване на всяка оферта или подобрение на пътя до запитване. При цел за продажби уточняваме началните показатели и периода на измерване преди плащането.' },
      { q: 'Трябва ли да сменим сайта или екипа?', a: 'Първо проверяваме какво вече работи и какво може да се подобри. За стартовия проект използваме съществуващия сайт и достъпните инструменти, когато това е технически възможно. Нов цял сайт или преместване в друга платформа не са включени в тази цена.' },
      { q: 'Какво означават CRM, автоматизация и AI?', a: 'CRM е подреден списък с контакти, разговори и оферти. Автоматизацията изпълнява повтаряща се стъпка — например напомняне да се обадите. AI означава изкуствен интелект и може да помага с чернови или обобщения, които човек проверява. Избираме инструмента според задачата.' },
      { q: 'Има ли допълнителни месечни разходи?', a: 'Няма задължителен абонамент към KARCHX след стартовия проект. Някои външни инструменти имат собствена такса. Ако са нужни, уточняваме кои са, колко струват и кой ги плаща, преди да ги активираме.' },
      { q: 'Какво трябва да подготвя?', a: 'Линк към бизнеса, кратко описание на услугата и няколко примера как получавате и обработвате запитвания. За започване ще уточним нужните достъпи и човек за обратна връзка. Не изпращайте пароли или чувствителни клиентски данни през формата.' },
      { q: 'Какво става след постигане на целите?', a: 'Получавате договореното изпълнение, инструкции и обучение. Може да продължите самостоятелно или да обсъдим следващи подобрения. Няма задължителен месечен абонамент.' },
    ],
  },
  en: {
    title: 'From an enquiry', titleSecond: 'to a new customer.',
    intro: 'I help established businesses explain their offer, respond promptly and follow up on enquiries. We improve your website, content and sales process around the point where potential customers get stuck.',
    cta: 'Request a free first call', note: '30 minutes by phone · Free · No obligation',
    promises: ['Clear scope and price', 'Implementation included', 'Work directly with me'],
    differenceTitle: 'Where does your', differenceSecond: 'business get stuck?',
    differenceIntro: 'We choose the problem that matters most to your business. Here are the areas we can improve to address it.',
    principles: [
      { title: 'People do not know why to choose you', text: 'Clarify who your service is for, what customers receive and why it matters. Rewrite your offer and key messages around concrete benefits and a clear next step.' },
      { title: 'Your website gets visits, but few enquiries', text: 'Check the mobile experience, structure, evidence, buttons and form. Fix the obstacles to calling, enquiring or booking.' },
      { title: 'Enquiries get lost in messages', text: 'Keep contacts and proposals in one place. Give each conversation an owner, a stage and a next action so follow-up is visible.' },
      { title: 'Content has no clear purpose', text: 'Plan topics, messages and calls to action around your services. Create a practical plan and reusable templates for your team.' },
      { title: 'Repetitive work slows you down', text: 'Set up relevant notifications, follow-up reminders and summaries. Use AI where it saves work and its output can be checked.' },
      { title: 'Everything depends on the founder', text: 'Define responsibilities and next steps. Create short instructions, train the team and track a few useful measures.' },
    ],
    offerTitle: 'I do not sell a package.', offerSecond: 'I sell two weeks.',
    offerIntro: 'You pick the one thing holding you back most. We put it in writing before you pay. Then I work on it for two weeks.',
    priceLabel: 'One-off fee for the first 3 clients',
    scope: [
      'A call where we go through your business and pick what is slowing you down most right now.',
      'The scope in writing before payment: what I will do, where it ends and how we check it is done.',
      'Two weeks of work on what you picked — a site, a page, an offer, copy, ads, content, automation or an internal process.',
      'Everything built stays yours: access, files, copy and settings, registered in your name.',
      'A test with a real case from start to finish, not in theory.',
      '45 minutes of training and short instructions, so you can carry on without me.',
    ],
    offerTiming: 'Two weeks of work from the agreed start date.',
    offerPayment: '€250 paid in full upfront, once the scope is agreed in writing.',
    offerWhy: 'If the agreed goals are not achieved after two weeks, we continue working towards them completely free until they are achieved. There is no additional fee for our work on these goals.',
    offerCta: 'Discuss the introductory project',
    guideTitle: 'Before we talk,', guideSecond: 'check for yourself.',
    guideIntro: '“12 checks: where enquiries get lost” — a practical Bulgarian guide to your offer, website and follow-up. Identify gaps and choose one improvement for this week.',
    guideBullets: ['12 questions with practical actions', 'Sample first response and follow-up', 'A worksheet for your first improvement'],
    guideRead: 'Read the Bulgarian checklist', guideDownload: 'Download PDF', guideNote: 'Free · No registration · In Bulgarian',
    aboutTitle: 'The person', aboutSecond: 'you will work with.',
    aboutText: 'I’m Georgi Karchev, founder of KARCHX. My work combines websites, content, marketing and automation. You work directly with me from the first call to handover. If you already have a designer, marketer or salesperson, we involve them with clear tasks and responsibilities.',
    role: 'Georgi Karchev', roleDetail: 'Founder of KARCHX · Plovdiv / remote across Bulgaria',
    faqTitle: 'Before you decide.',
    faqs: [
      { q: 'Who is this for?', a: 'An established business with customers, an offer and someone available to participate. It is most useful when visits or enquiries already exist but handling them is fragmented. A business still deciding what to sell is usually not ready for this project.' },
      { q: 'Is the first call free?', a: 'Yes. It takes up to 30 minutes by phone with no purchase obligation. We discuss your business and whether there is a suitable task. Detailed diagnosis and implementation belong to the paid project.' },
      { q: 'What does €250 cover, and when do I pay?', a: 'Two weeks of work within the stated scope, for the first 3 clients. Payment is made in full upfront. We document the goals, success measures, tasks and start date before payment. Any external costs require separate agreement.' },
      { q: 'What if the goals take longer than two weeks?', a: 'We continue working towards the goals agreed before starting, completely free until they are achieved. New tasks outside those goals are discussed separately. External tool fees are separate from our work and agreed in advance.' },
      { q: 'How are the goals defined?', a: 'We review your business and available data, then document the goals and how achievement will be verified. Examples include response time, consistent proposal follow-up and a better enquiry journey. For sales goals, we agree on the baseline and measurement period before payment.' },
      { q: 'Will we need a new website or team?', a: 'We first check what can be improved. The introductory scope uses your existing website and available tools where technically possible. A full rebuild or platform migration is not included.' },
      { q: 'What are CRM, automation and AI?', a: 'A CRM tracks contacts, conversations and proposals. Automation handles repeatable steps such as reminders. AI can prepare drafts or summaries for human review. We choose tools to fit the task.' },
      { q: 'Are there recurring costs?', a: 'There is no mandatory KARCHX retainer. External tools may have their own fees. We agree on the tools, prices and who pays before activating them.' },
      { q: 'What should I prepare?', a: 'A business link, a short service description and examples of how enquiries are handled. We agree on access and a feedback contact before starting. Do not submit passwords or sensitive customer data through the form.' },
      { q: 'What happens after achieving the goals?', a: 'You receive the agreed work, instructions and training. Continue independently or discuss further improvements. There is no mandatory monthly retainer.' },
    ],
  },
}
