export const growthContent = {
  bg: {
    title: 'От запитване', titleSecond: 'до нов клиент.',
    intro: 'Помагам на работещи бизнеси да представят по-ясно офертата си, да отговарят навреме и да проследяват всяко запитване. Подреждаме сайта, съдържанието и продажбите според това къде се губи клиентът.',
    cta: 'Заявете безплатен разговор', note: '30 минути по телефона · Без плащане и без ангажимент',
    promises: ['Ясен обхват и цена', 'Изпълнение, не само съвети', 'Работите директно с мен'],
    differenceTitle: 'Къде се затруднява', differenceSecond: 'Вашият бизнес?',
    differenceIntro: 'Избираме проблема с най-голямо значение за Вас. Ето какво можем да подобрим според нуждите на бизнеса.',
    principles: [
      { title: 'Хората не разбират защо да изберат Вас', text: 'Изясняваме за кого е услугата Ви, какво получава клиентът и защо си струва. Пренаписваме офертата и ключовите текстове с конкретни ползи и ясна следваща стъпка.' },
      { title: 'Имате посещения, но малко запитвания', text: 'Проверяваме страницата на телефон, подредбата, доказателствата, бутоните и формата. Поправяме пречките пред обаждането, запитването или записването.' },
      { title: 'Запитванията се губят в съобщенията', text: 'Събираме контактите и офертите на едно място. Всеки разговор има отговорник, етап и следваща задача, за да знаете на кого още трябва да отговорите.' },
      { title: 'Публикувате, без да е ясно с каква цел', text: 'Подреждаме темите, посланията и призивите за действие около услугите Ви. Подготвяме план и шаблони, които Вашият екип може да използва последователно.' },
      { title: 'Повтарящите се задачи Ви бавят', text: 'Настройваме подходящи автоматизации: известия за ново запитване, напомняния за оферти и обобщения. Използваме изкуствен интелект там, където пести работа и може да бъде проверен.' },
      { title: 'Всичко минава през собственика', text: 'Описваме кой какво прави и кога. Даваме кратки инструкции, обучаваме хората и следим няколко полезни показателя вместо куп несвързани отчети.' },
    ],
    offerTitle: 'Първа стъпка.', offerSecond: 'С ясна цена.',
    offerIntro: 'Две седмици фокусирана работа по бизнеса Ви. Преди старта уговаряме целите, задачите и как ще измерим постигнатото.',
    priceLabel: 'Еднократно за първите 3 клиента',
    scope: [
      'Преглед на една оферта, една страница и начина, по който обработвате запитванията.',
      'По-ясна оферта и преработка на една ключова секция от съществуващия Ви сайт, ако имаме достъп за редакция.',
      'Едно място за проследяване на запитванията — с етапи, отговорник и следваща задача.',
      'Три готови текста: първи отговор, изпращане на оферта и последващо свързване.',
      'До две базови автоматизации за известие или напомняне, когато избраните инструменти го позволяват.',
      'Тест на целия път, 45 минути обучение и кратки инструкции за Вас и екипа.',
    ],
    offerTiming: 'Две седмици работа от договорената начална дата.',
    offerPayment: '250 € се заплащат предварително, след писмено уточняване на целите и обхвата.',
    offerBoundary: 'Тази цена е за описания обхват. Нов цял сайт, рекламни кампании, ежедневно съдържание и сложни интеграции се обсъждат отделно. Външни абонаменти се добавят само след предварително съгласуване на цената им.',
    offerWhy: 'Ако след двете седмици договорените цели не са постигнати, продължаваме да работим по тях напълно безплатно, докато ги постигнем. Няма допълнителна такса за работата ни по тези цели.',
    offerCta: 'Да обсъдим стартовия проект',
    processTitle: 'Знаете какво', processSecond: 'следва.',
    processIntro: 'Преди да започнем, уточняваме какво ще получите и как ще проверим работата. Ако този проект не е подходящ за бизнеса Ви, ще го кажа още в първия разговор.',
    steps: [
      { title: 'Разговор за бизнеса Ви', text: 'За 30 минути обсъждаме какво продавате, откъде идват запитванията и къде срещате трудности. Подгответе линк към сайта или профила си.' },
      { title: 'Писмен обхват и отправна точка', text: 'Уточняваме задачите, достъпите, срока и цената. Записваме начални показатели: например време за отговор и колко запитвания стигат до оферта.' },
      { title: 'Изграждане и проверка', text: 'Внедрявам договорените промени с Ваше участие. Пробваме реалистично запитване от начало до край и поправяме откритите проблеми.' },
      { title: 'Предаване и следващи стъпки', text: 'Показвам на Вас и екипа как да използвате процеса. Получавате инструкции и план как да следите резултата. За оценка на продажбите е нужен достатъчен брой реални запитвания.' },
    ],
    guideTitle: 'Преди да говорим,', guideSecond: 'проверете сами.',
    guideIntro: '„12 проверки: къде губите запитвания“ — кратко практическо ръководство за офертата, сайта и отговора към клиента. Отбележете пропуските и изберете една стъпка за тази седмица.',
    guideBullets: ['12 въпроса с конкретни действия', 'Пример за първи отговор и последващо свързване', 'Работен лист за първото подобрение'],
    guideRead: 'Прочетете чеклиста', guideDownload: 'Свалете PDF', guideNote: 'Безплатно · Без регистрация · На български',
    aboutTitle: 'Човекът, с когото', aboutSecond: 'ще работите.',
    aboutText: 'Аз съм Георги Кърчев, основател на KARCHX. Съчетавам работа по сайтове, съдържание, маркетинг и автоматизации. Ще работите директно с мен — от първия разговор до предаването. Ако вече имате дизайнер, маркетолог или търговец, включваме го с ясни задачи и отговорности.',
    role: 'Георги Кърчев', roleDetail: 'Основател на KARCHX · Пловдив / онлайн за България',
    faqTitle: 'Отговори преди решението.',
    faqs: [
      { q: 'За какъв бизнес е подходящо?', a: 'За работещ бизнес с реални клиенти, услуга или продукт и човек, който може да участва във внедряването. Най-полезно е, когато вече има посещения или запитвания, но обработката им е разпокъсана. Ако тепърва търсите какво да продавате, този стартов проект вероятно не е първата Ви стъпка.' },
      { q: 'Безплатен ли е първият разговор?', a: 'Да. Той е до 30 минути, по телефона и без ангажимент за покупка. Обсъждаме бизнеса и преценяваме дали има подходяща задача. Подробният преглед и изпълнението са част от платения проект.' },
      { q: 'Какво включва цената 250 € и кога се плаща?', a: 'Цената е за две седмици работа по описания обхват и важи за първите 3 клиента. Плаща се изцяло предварително. Преди плащането записваме целите, как ще измерим изпълнението им, задачите и началната дата. Евентуални външни разходи се съгласуват отделно.' },
      { q: 'Какво става, ако целите не са постигнати за две седмици?', a: 'Продължаваме да работим по предварително договорените цели напълно безплатно, докато ги постигнем. Този ангажимент е за целите, записани преди старта. Нови задачи извън тях се обсъждат отделно. Цените на външни инструменти не са такса за нашата работа и се уточняват предварително.' },
      { q: 'Как определяме целите?', a: 'В началото преглеждаме бизнеса и наличните данни. Записваме конкретните цели и начина, по който ще проверим постигането им: например време за отговор, проследяване на всяка оферта или подобрение на пътя до запитване. При цел за продажби уточняваме началните показатели и периода на измерване преди плащането.' },
      { q: 'Трябва ли да сменим сайта или екипа?', a: 'Първо проверяваме какво вече работи и какво може да се подобри. За стартовия проект използваме съществуващия сайт и достъпните инструменти, когато това е технически възможно. Нов цял сайт или преместване в друга платформа не са включени в тази цена.' },
      { q: 'Какво означават CRM, автоматизация и AI?', a: 'CRM е подреден списък с контакти, разговори и оферти. Автоматизацията изпълнява повтаряща се стъпка — например напомняне да се обадите. AI означава изкуствен интелект и може да помага с чернови или обобщения, които човек проверява. Избираме инструмента според задачата.' },
      { q: 'Има ли допълнителни месечни разходи?', a: 'Няма задължителен абонамент към KARCHX след стартовия проект. Някои външни инструменти имат собствена такса. Ако са нужни, уточняваме кои са, колко струват и кой ги плаща, преди да ги активираме.' },
      { q: 'Какво трябва да подготвя?', a: 'Линк към бизнеса, кратко описание на услугата и няколко примера как получавате и обработвате запитвания. За започване ще уточним нужните достъпи и човек за обратна връзка. Не изпращайте пароли или чувствителни клиентски данни през формата.' },
      { q: 'Какво става след постигане на целите?', a: 'Получавате договореното изпълнение, инструкции и обучение. Може да продължите самостоятелно или да обсъдим следващи подобрения. Няма задължителен месечен абонамент.' },
    ],
  },
  en: {
    title: 'From an enquiry', titleSecond: 'to a new customer.',
    intro: 'I help established businesses explain their offer, respond promptly and follow up on enquiries. We improve your website, content and sales process around the point where potential customers get stuck.',
    cta: 'Request a free first call', note: '30 minutes by phone · Free · No obligation',
    promises: ['Clear scope and price', 'Implementation included', 'Work directly with me'],
    differenceTitle: 'Where does your', differenceSecond: 'business get stuck?',
    differenceIntro: 'We choose the problem that matters most to your business. Here are the areas we can improve to address it.',
    principles: [
      { title: 'People do not know why to choose you', text: 'Clarify who your service is for, what customers receive and why it matters. Rewrite your offer and key messages around concrete benefits and a clear next step.' },
      { title: 'Your website gets visits, but few enquiries', text: 'Check the mobile experience, structure, evidence, buttons and form. Fix the obstacles to calling, enquiring or booking.' },
      { title: 'Enquiries get lost in messages', text: 'Keep contacts and proposals in one place. Give each conversation an owner, a stage and a next action so follow-up is visible.' },
      { title: 'Content has no clear purpose', text: 'Plan topics, messages and calls to action around your services. Create a practical plan and reusable templates for your team.' },
      { title: 'Repetitive work slows you down', text: 'Set up relevant notifications, follow-up reminders and summaries. Use AI where it saves work and its output can be checked.' },
      { title: 'Everything depends on the founder', text: 'Define responsibilities and next steps. Create short instructions, train the team and track a few useful measures.' },
    ],
    offerTitle: 'A first step.', offerSecond: 'A clear price.',
    offerIntro: 'Two weeks of focused work on your business. Before starting, we agree on the goals, tasks and how progress will be measured.',
    priceLabel: 'One-off fee for the first 3 clients',
    scope: [
      'Review one offer, one page and your enquiry handling process.',
      'Clarify the offer and rewrite one key section of your existing website, subject to editing access.',
      'Set up one enquiry tracker with stages, an owner and a next action.',
      'Write three templates: first response, proposal and follow-up.',
      'Configure up to two basic notifications or reminders where your chosen tools support them.',
      'Test the full journey, deliver 45 minutes of training and short instructions for your team.',
    ],
    offerTiming: 'Two weeks of work from the agreed start date.',
    offerPayment: '€250 paid in full upfront, after agreeing on goals and scope in writing.',
    offerBoundary: 'The price covers this scope. A complete new website, ad campaigns, daily content and complex integrations are quoted separately. External subscriptions require advance agreement on their cost.',
    offerWhy: 'If the agreed goals are not achieved after two weeks, we continue working towards them completely free until they are achieved. There is no additional fee for our work on these goals.',
    offerCta: 'Discuss the introductory project',
    processTitle: 'Know what', processSecond: 'comes next.',
    processIntro: 'Before starting, we agree on the deliverables and how to check the work. If this project is not a good fit, I will say so during the first call.',
    steps: [
      { title: 'Discuss your business', text: 'In 30 minutes, we discuss your services, enquiries and obstacles. Have a link to your website or business profile ready.' },
      { title: 'Agree on scope and baseline', text: 'Document the tasks, access, timeline and price. Record relevant measures such as response time and enquiries reaching a proposal.' },
      { title: 'Implement and test', text: 'I build the agreed changes with your input. We test a realistic enquiry from start to finish and address the issues we find.' },
      { title: 'Hand over and measure', text: 'Train you and your team, provide instructions and agree how to monitor progress. Evaluating sales requires enough real enquiries.' },
    ],
    guideTitle: 'Before we talk,', guideSecond: 'check for yourself.',
    guideIntro: '“12 checks: where enquiries get lost” — a practical Bulgarian guide to your offer, website and follow-up. Identify gaps and choose one improvement for this week.',
    guideBullets: ['12 questions with practical actions', 'Sample first response and follow-up', 'A worksheet for your first improvement'],
    guideRead: 'Read the Bulgarian checklist', guideDownload: 'Download PDF', guideNote: 'Free · No registration · In Bulgarian',
    aboutTitle: 'The person', aboutSecond: 'you will work with.',
    aboutText: 'I’m Georgi Karchev, founder of KARCHX. My work combines websites, content, marketing and automation. You work directly with me from the first call to handover. If you already have a designer, marketer or salesperson, we involve them with clear tasks and responsibilities.',
    role: 'Georgi Karchev', roleDetail: 'Founder of KARCHX · Plovdiv / remote across Bulgaria',
    faqTitle: 'Before you decide.',
    faqs: [
      { q: 'Who is this for?', a: 'An established business with customers, an offer and someone available to participate. It is most useful when visits or enquiries already exist but handling them is fragmented. A business still deciding what to sell is usually not ready for this project.' },
      { q: 'Is the first call free?', a: 'Yes. It takes up to 30 minutes by phone with no purchase obligation. We discuss your business and whether there is a suitable task. Detailed diagnosis and implementation belong to the paid project.' },
      { q: 'What does €250 cover, and when do I pay?', a: 'Two weeks of work within the stated scope, for the first 3 clients. Payment is made in full upfront. We document the goals, success measures, tasks and start date before payment. Any external costs require separate agreement.' },
      { q: 'What if the goals take longer than two weeks?', a: 'We continue working towards the goals agreed before starting, completely free until they are achieved. New tasks outside those goals are discussed separately. External tool fees are separate from our work and agreed in advance.' },
      { q: 'How are the goals defined?', a: 'We review your business and available data, then document the goals and how achievement will be verified. Examples include response time, consistent proposal follow-up and a better enquiry journey. For sales goals, we agree on the baseline and measurement period before payment.' },
      { q: 'Will we need a new website or team?', a: 'We first check what can be improved. The introductory scope uses your existing website and available tools where technically possible. A full rebuild or platform migration is not included.' },
      { q: 'What are CRM, automation and AI?', a: 'A CRM tracks contacts, conversations and proposals. Automation handles repeatable steps such as reminders. AI can prepare drafts or summaries for human review. We choose tools to fit the task.' },
      { q: 'Are there recurring costs?', a: 'There is no mandatory KARCHX retainer. External tools may have their own fees. We agree on the tools, prices and who pays before activating them.' },
      { q: 'What should I prepare?', a: 'A business link, a short service description and examples of how enquiries are handled. We agree on access and a feedback contact before starting. Do not submit passwords or sensitive customer data through the form.' },
      { q: 'What happens after achieving the goals?', a: 'You receive the agreed work, instructions and training. Continue independently or discuss further improvements. There is no mandatory monthly retainer.' },
    ],
  },
}
